# Generated by Django 2.2.7 on 2019-11-23 11:41

import django.contrib.postgres.fields.citext
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=django.contrib.postgres.fields.citext.CITextField(unique=True),
        ),
    ]
