# Generated by Django 3.0.2 on 2020-01-15 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20191123_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfile',
            name='dropbox_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
